# Automatically generated by Simple_ROS_Configurator
# Simple_ROS_Configurator: !SRC_LINK!
# Generated via !GEN_METHOD!
#
# License: CC BY 4.0
# Get your copy at
# https://creativecommons.org/licenses/by/4.0/

import rclpy
from rclpy.node import Node

from std_msgs.msg import String

# import and "construct" neccessary types
from typing import Callable
from typing import TypeVar

MsgType = TypeVar('MsgType')


class _Sub:
    """
    TODO doc
    """
    name: str
    msg_type: MsgType
    topic: str
    callback: Callable[[MsgType], None]

    def __init__(self, name: str, msg_type: MsgType, topic: str, callback: Callable[[MsgType], None]):
        """
        Init an instance of the Subscription/Publication class _Sub
        :param name: Name for this instance.
        :param msg_type: Type of message to be published / received.
        :param topic: Name of the topic to post / listen to.
        :param callback: Method to be called when message was received. Ignored if class is used as publisher.
        """
        self.name = name
        self.msg_type = msg_type
        self.topic = topic
        self.callback = callback


subs: [_Sub]

subs = []


class Subscriber(Node):

    def __init__(self, sub: _Sub):
        super().__init__(sub.name)
        self.subscription = self.create_subscription(
            sub.msg_type,
            sub.topic,
            sub.callback,
            10)
        self.subscription  # prevent unused variable warning


def main(args=None):
    rclpy.init(args=args)
    minimal_subscriber = Subscriber()
    rclpy.spin(minimal_subscriber)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    minimal_subscriber.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()